from __future__ import annotations


DEFAULT_PROFILE = {
    "name": "General Presentation",
    "subtitle": "presentation profile",
    "sections": [
        "Overview",
        "Context",
        "Key Themes",
        "Evidence",
        "Milestones",
        "Impact",
        "Details",
        "Implications",
        "Highlight",
        "Takeaways",
    ],
    "closing": "Key Takeaways",
}


TEMPLATE_PROFILES = {
    "template-1-4": {
        "name": "Creative Portfolio",
        "subtitle": "profile",
        "sections": [
            "Introduction",
            "Background",
            "Key Themes",
            "Major Milestones",
            "Impact Summary",
            "Project Focus",
            "Notable Influence",
            "Best Highlight",
            "Key Takeaways",
        ],
        "closing": "Key Takeaways",
    },
    "template-1-5": {
        "name": "Creative Portfolio",
        "subtitle": "profile",
        "sections": [
            "Introduction",
            "Background",
            "Key Themes",
            "Major Milestones",
            "Impact Summary",
            "Project Focus",
            "Notable Influence",
            "Best Highlight",
            "Key Takeaways",
        ],
        "closing": "Key Takeaways",
    },
    "visual-f": {
        "name": "Pitch Deck",
        "subtitle": "pitch profile",
        "sections": [
            "Agenda",
            "Problem",
            "Products",
            "Market Context",
            "Customer Need",
            "Solution",
            "Business Model",
            "Traction",
            "Competitive Edge",
            "Go-To-Market",
            "Roadmap",
            "Financial Logic",
            "Risks",
            "Next Steps",
            "Closing",
        ],
        "closing": "Next Steps",
    },
    "diagram-infographics": {
        "name": "Infographic Analysis",
        "subtitle": "systems analysis",
        "sections": [
            "Decision Landscape",
            "Signal Flow",
            "Biases And Risks",
            "Trade-Offs",
            "Dependencies",
            "Operating Model",
            "Feedback Loops",
            "Priority Map",
            "Execution Path",
            "Takeaways",
        ],
        "closing": "Takeaways",
    },
    "tell-tale": {
        "name": "Narrative Portfolio",
        "subtitle": "profile",
        "sections": [
            "About",
            "Background",
            "Experience",
            "Projects",
            "Process",
            "Selected Work",
            "Capabilities",
            "Contact",
            "Closing",
        ],
        "closing": "Closing",
    },
    "minimal": {
        "name": "Minimal Brief",
        "subtitle": "strategic brief",
        "sections": [
            "Overview",
            "Agenda",
            "Context",
            "Main Point",
            "Problem",
            "Evidence",
            "Insight",
            "Solution",
            "Benefits",
            "Timeline",
            "Risks",
            "Details",
            "Action Plan",
            "Summary",
            "Next Steps",
        ],
        "closing": "Next Steps",
    },
    "comicbook": {
        "name": "Comic Story",
        "subtitle": "story deck",
        "sections": [
            "Opening",
            "The Setup",
            "The Challenge",
            "The Turn",
            "The Stakes",
            "The Breakthrough",
            "The Result",
            "The Lesson",
            "The Reveal",
            "Final Beat",
        ],
        "closing": "Final Beat",
    },
    "elegant-editorial": {
        "name": "Editorial Report",
        "subtitle": "editorial brief",
        "sections": [
            "Executive View",
            "Context",
            "Key Insight",
            "Evidence",
            "By The Numbers",
            "Implications",
            "Comparison",
            "Recommendation",
            "Action Plan",
            "Closing Thought",
        ],
        "closing": "Closing Thought",
    },
    "mario-zelgalolyfok15dijfjzrgyonjdf5k": {
        "name": "Playful Deck",
        "subtitle": "visual brief",
        "sections": [
            "Opening",
            "Overview",
            "Challenge",
            "Context",
            "Evidence",
            "Ideas",
            "Execution",
            "Impact",
            "Next Move",
            "Wrap Up",
        ],
        "closing": "Wrap Up",
    },
    "microsoft-fundamentals-series-2026-aesthetic": {
        "name": "Single Slide Summary",
        "subtitle": "summary brief",
        "sections": ["Summary"],
        "closing": "Summary",
    },
    "iot": {
        "name": "Technology Brief",
        "subtitle": "technology profile",
        "sections": [
            "Overview",
            "Context",
            "Themes",
            "Evidence",
            "Milestones",
            "Impact",
            "Details",
            "Risks",
            "Signal",
            "Takeaways",
        ],
        "closing": "Takeaways",
    },
    "roadmap": {
        "name": "Roadmap Brief",
        "subtitle": "strategy profile",
        "sections": [
            "Overview",
            "Context",
            "Themes",
            "Evidence",
            "Phases",
            "Impact",
            "Details",
            "Actions",
            "Risks",
            "Takeaways",
        ],
        "closing": "Takeaways",
    },
    "startup": {
        "name": "Startup Brief",
        "subtitle": "business profile",
        "sections": [
            "Overview",
            "Context",
            "Themes",
            "Evidence",
            "Milestones",
            "Impact",
            "Details",
            "Signals",
            "Focus",
            "Takeaways",
        ],
        "closing": "Takeaways",
    },
    "interior": {
        "name": "Design Brief",
        "subtitle": "design brief",
        "sections": [
            "Intro",
            "Context",
            "Themes",
            "Proof",
            "Steps",
            "Impact",
            "Details",
            "Signals",
            "Focus",
            "Takeaways",
        ],
        "closing": "Takeaways",
    },
    "architecture": {
        "name": "Visual Brief",
        "subtitle": "strategy profile",
        "sections": [
            "Overview",
            "Context",
            "Themes",
            "Evidence",
            "Milestones",
            "Impact",
            "Details",
            "Signals",
            "Focus",
            "Takeaways",
        ],
        "closing": "Takeaways",
    },
    "product": {
        "name": "Product Brief",
        "subtitle": "product profile",
        "sections": [
            "Overview",
            "Context",
            "Themes",
            "Evidence",
            "Milestones",
            "Impact",
            "Details",
            "Signals",
            "Focus",
            "Takeaways",
        ],
        "closing": "Takeaways",
    },
}


def get_template_profile(template_id: str | None) -> dict:
    if not template_id:
        return DEFAULT_PROFILE
    return TEMPLATE_PROFILES.get(template_id, DEFAULT_PROFILE)
